sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start creating image ( docker ) "
  - docker build -t mickey1102/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mickey1102/docker-react npm run test -- --coverage

after_success:
  - echo "Test success DONNNNE"
